# setting.toml
# 各種設定・環境変数はここで設定
[game_option]
# 固定FPS数値
constant_fps = 60

[assets]
# アセットフォルダ設定
# 読み込むアセットが入ったフォルダ名を指定
# デフォルト設定は`assets`
assets_dir = "assets"

[translate]
# 翻訳設定
# `is_translate`を`true`にすると、
# `translate_data_dir`で指定したフォルダから翻訳データを読み込む
is_translate = false

# 翻訳データフォルダ設定
# 翻訳データ側に`assets`フォルダ内データと同名ファイルがあった場合、
# 翻訳データ側が使用される（読み込み元を上書きする）
translate_data_dir = "tl/english"
